import AppMUIConfigProvider from "@/MUIconfigProvider";
import AppProvider from "@/appProvider";
import "./globals.css";
import dotenv from "dotenv";
// import ServerErrorHandler from "@/api/api.ErrorHandler"


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fn" dir="rtl">
      <body>
        {/* <AppMUIConfigProvider> */}
        <AppProvider>
          {/* <ServerErrorHandler /> */}
          {children}
        </AppProvider>
        {/* </AppMUIConfigProvider> */}
      </body>
    </html>
  );
}
